### ISSUE TITLE
Obfuscated?

### ISSUE THREAD

**Issue by Chosey98** [ItsMrReals/rBot#6]
**Describe the bug**
Suddenly the code is obfuscated on the server.js, How can I make sure you don't have malicious stuff in there? It is just weird to see something like that

**Comment by ItsMrReals** [comment]
If you think it’s malicious  deobfuscate it but it’s that we have had people who resell so I put all the security code in there and also the code to run the bot so if they delete it then they can’t use the bot.

**Comment by Chosey98** [comment]
I see good job on it
